# Generated by Django 2.1.3 on 2018-12-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesDatabase', '0002_auto_20181208_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecast',
            old_name='actor_id',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='moviecast',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
