# Generated by Django 2.1.3 on 2018-12-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesDatabase', '0003_auto_20181208_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecast',
            name='role',
            field=models.CharField(choices=[('lead', 'Lead'), ('supportive', 'Supporting'), ('featured', 'Featured'), ('background', 'Background')], max_length=15),
        ),
    ]
